### ISSUE TITLE
workspaces with unpublished path dependencies result in an error

### ISSUE THREAD

**Issue by lopopolo** [the-lean-crate/cargo-diet#3]
When deserialized, this is the error message:

> error: no matching package named `artichoke-backend` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `artichoke v0.1.0-pre.0 (/Users/lopopolo/dev/artichoke/artichoke)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag

**Comment by Byron** [comment]
Thank you! I am closing this one in favor of #2.
