### ISSUE TITLE
Cargo include directive mis-interpretation

### ISSUE THREAD

**Issue by darnuria** [the-lean-crate/cargo-diet#6]
Hello thanks for the tool!

I am not sure but It look like there is an issue with include directives in cargo or in their interpretation in `cargo diet`

I added theses lines in the https://github.com/mongodb/bson-rust/pull/203 crate like suggested by `cargo diet`:

```toml
include = [
    "Cargo.toml",
    "src/**/*",
    "LICENSE",
    "README.md",
    "!**/tests/*"
]
```

In this case only the first files in `src/tests` will be not included.

And tests files in sub-folders of `src/tests` are still in the package under `src` after a `cargo publish --dry-run`

the rule: `"!**/tests/**/*"` seems to do the trick.

But cargo-diet analysis seems happy.

**Comment by Byron** [comment]
Thanks so much for reporting! This definitely is a bug, and I wasn't aware until now.
Will take a look right away!

**Comment by Byron** [comment]
Fixed with v1.1.5 .

It's so great to see `cargo-diet` being picked up and used. And even though in the end maintainers may prefer a different way of writing the globs, at least it gets the conversation started and makes it easy to see the potential for slimming down a crate.

**Comment by darnuria** [comment]
Thanks, nice tool to check size usage by files, looking "by hand" in `target/package` is not straight forward. Have a nice weekend.

**Comment by Byron** [comment]
I was quite inspired by the idea of actually listing files in the crate, so in `cargo-diet` 1.2.0, there is now a new `--list` flag which does just that. It works in conjunction with the other flags, and really just dumps the last N biggest entries in the crate.
