### ISSUE TITLE
Feature: Automatically use lto in release

### ISSUE THREAD

**Issue by Milo123459** [the-lean-crate/cargo-diet#8]
Just automatically add:
```toml
[profile.release]
lto = "fat"
```

**Comment by Byron** [comment]
No argument was provided to explain why this would be valuable.
When thinking about this, I can only come up with an argument against such feature: `cargo diet` is about keeping crates packages small, it isn't concerned with binary size.

Please feel free to provide arguments on the closed issue though, maybe I am not seeing something.

**Comment by Milo123459** [comment]
Well, if you can make the binary smaller, isn't the crate smaller? Or am I missing something?

**Comment by Byron** [comment]
> Well, if you can make the binary smaller, isn't the crate smaller?

The crate is a package containing source code to build the binary or other artifacts, not every crate produced binaries. `cargo diet` only means to slim down the amount of source code shipped in these crates and leaves configuring artifacts entirely to the crate owners. Changing build settings really isn't anything where one size fits all.

**Comment by Milo123459** [comment]
I see, I think I must've misunderstood a few things along the line.. Mb!
